version: "3"
services: 
  django_dev_env:
    image: python:latest
    container_name: django-docker
    entrypoint: /bin/bash
    working_dir: /home/app
    ports:
      - 5000:8000
    volumes: 
      - ./server:/home/app
    depends_on: 
      - mysql_db
  react_dev_env:
    image: node:latest
    container_name: react-docker
    entrypoint: /bin/bash
    working_dir: /home/app
    environment: 
      - PORT=3500
    ports: 
      - 3500:3500
    volumes: 
      - ./client:/home/app
  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql-docker
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_DATABASE=netflix
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes: 
      - ./db/data:/var/lib/mysql